name: Build KernelSU Next EvolutionX Final Success
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          ref: vic

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential flex bison libssl-dev libelf-dev clang lld llvm crossbuild-essential-arm64 curl git

      - name: Setup KSU Next (Verified Patch)
        run: |
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
          cd drivers/kernelsu
          git fetch --tags
          git checkout v3.0.1
          # الإصلاح الذي نجح في تجاوز ملفات الروت
          echo "#define TWA_RESUME 1" >> ksu.h
          echo "#define TWA_SIGNAL 0" >> ksu.h
          cd ../..

      - name: Build Kernel (Fixing Net & Root)
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CC=clang
          export LD=ld.lld
          make O=out clean
          make O=out exynos9820-f62_defconfig
          
          # تفعيل ميزات الروم المعدل
          scripts/config --file out/.config --enable CONFIG_OVERLAY_FS
          scripts/config --file out/.config --enable CONFIG_KSU
          
          # إضافة باراميترات قوية لتجاهل تضارب "الشبكة" في أندرويد 16
          # أضفنا -Wno-unused-but-set-variable و -Wno-implicit-fallthrough
          make O=out KCFLAGS="-Wno-error -Wno-implicit-function-declaration -Wno-strict-prototypes -Wno-incompatible-pointer-types -Wno-unused-but-set-variable -Wno-implicit-fallthrough" -j$(nproc)

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_M62_Next_EvoX_A16
          path: out/arch/arm64/boot/Image*
          
